const TableHeaderEnum = Object.freeze({
  GAINER_24HR: 'GAINER_24HR',
  GAINER_10MIN: 'GAINER_10MIN',
  LOSER_24HR: 'LOSER_24HR',
  ACTIVE_24HR: 'ACTIVE_24HR',
  TVL_UP_24HR: 'TVL_UP_24HR',
  TVL_DOWN_24HR: 'TVL_DOWN_24HR',
  NEWEST_LISTING: 'NEWEST_LISTING',
  TOP_DEXs: 'TOP_DEXs'
});

module.exports = TableHeaderEnum